---
my:
  data:
    # REQUIRED: used by the git playbook
    fullname: root
    # REQUIRED: used by intellij playbooks, it must be the same one used to login into your computer
    username: root
    # REQUIRED: used by the git playbook
    email: user@user.com

  playbooks: 
    java: true 
    golang: true 
    bazel: true
    maven: true 
    intellij: true 
    vscode: true
    docker: true 
    google_cloud_sdk: true
    git: true
    ruby: true
    protobuf: true 
    forticlient: true

  tools:
    java: 
      # Intellij's playbook uses both version, so don't remove them
      versions:
        - name: 8
          version: '8'
          default: no
        - name: 11 
          version: '11'
          default: yes
    maven:
      version: '3.6.3'
    bazel:
      version: '4.0.0'
      sha256: 'sha256:7bee349a626281fc8b8d04a7a0b0358492712377400ab12533aeb39c2eb2b901'
    golang:
      version: '1.16.2'
      sha256sum: '542e936b19542e62679766194364f45141fde55169db2d8d01046555ca9eb4b8'
      path: '$HOME/workspace-go'
    rvm:
      ruby:
        versions: 
          - ruby
          - 2.6.6
    docker_compose:
      version: '1.26.0'
    google_cloud_sdk:
      version: '335.0.0'
      components: pubsub-emulator app-engine-java beta
    protobuf:
      version: '3.10.0'
    forticlient:
      version: '6.4.3.0959'
    intellij:
      version: '2020.3.3'
      edition: ultimate # ultimate or community
      # You can get the sha256 at this link https://confluence.jetbrains.com/display/IDEADEV/Latest+builds or at roles/gantsign.intellij/vars/versions
      sha256: 'e7dbca1cbc34da19da4f58df44f599c128317a692dea8ac3977e594b36760baf'
      default_jdk: '11'
    vscode:
      settings: {
        'cSpell.language': 'en,pt,pt_BR',
        'cSpell.diagnosticLevel': 'Warning',
        'editor.minimap.enabled': 'false',
        'editor.tabSize': '2',
        'vetur.format.defaultFormatterOptions': {
          'prettier': {
            'singleQuote': true
          }
        },
        'vsintellicode.modify.editor.suggestSelection': 'automaticallyOverrodeDefaultValue',
        'workbench.editor.enablePreview': false,
        'workbench.startupEditor': 'newUntitledFile',
      }
      extensions:
        - dbaeumer.vscode-eslint
        - eamodio.gitlens
        - eg2.vscode-npm-script
        - esbenp.prettier-vscode
        - ms-azuretools.vscode-docker
        - ms-python.python
        - octref.vetur
        - vscjava.vscode-java-pack
        - streetsidesoftware.code-spell-checker
        - shd101wyy.markdown-preview-enhanced
        - streetsidesoftware.code-spell-checker-portuguese-brazilian
        - yzhang.markdown-all-in-one
        - vscoss.vscode-ansible
