---
- hosts: all
  become: yes
  vars:
    - bazel_platform: linux-x86_64
    - bazel_mirror: https://github.com/bazelbuild/bazel/releases/download
    - bazel_exe: bazel-{{ my.tools.bazel.version }}-linux-x86_64
    - bazel_exe_url: '{{ bazel_mirror }}/{{ my.tools.bazel.version }}/{{ bazel_exe }}'
    - bazel_install_dir: /usr/local/bin
    - bazel_install_path: '{{ bazel_install_dir }}/{{ bazel_exe }}'
    - bazel_link_path: '{{ bazel_install_dir }}/bazel'

  tasks:
    - name: Install BAZEL dependencies
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - pkg-config
        - zip
        - g++
        - zlib1g-dev
        - unzip

    - name: Download BAZEL
      get_url:
        url: '{{ bazel_exe_url }}'
        dest: '{{ bazel_install_path }}'
        checksum: '{{ my.tools.bazel.sha256 }}'
        mode: 0755

    - name: Link BAZEL
      file:
        src: '{{ bazel_install_path }}'
        dest: '{{ bazel_link_path }}'
        state: link

    - name: Install BUILDOZER
      shell: "/opt/go/{{ my.tools.golang.version }}/bin/go get github.com/bazelbuild/buildtools/buildozer"

    - name: Install BUILDFIER
      shell: "/opt/go/{{ my.tools.golang.version }}/bin/go get github.com/bazelbuild/buildtools/buildifier"

    - name: Install UNUSED_DEPS
      shell: "/opt/go/{{ my.tools.golang.version }}/bin/go get github.com/bazelbuild/buildtools/unused_deps"